### ISSUE TITLE
"glibc Alpine" is broken and shall not be used

### ISSUE THREAD

**Issue by catdevnull** [oven-sh/bun#1567]
As explained by one of Alpine's main developers, [glibc Alpine Linux is broken](https://ariadne.space/2021/08/26/there-is-no-such-thing-as-a-glibc-based-alpine-image/) and shouldn't be used. It is used in bun in the [Alpine container image](https://github.com/oven-sh/bun/blob/72f9017b21cbb6de83d054a0b985e9fe9a7708f3/dockerhub/Dockerfile-alpine#L13C9-L13C9)

**Comment by catdevnull** [comment]
related to #918

**Comment by catdevnull** [comment]
[Wolfi](https://www.chainguard.dev/unchained/introducing-wolfi-the-first-linux-un-distro) could be a good alternative as it was [suggested before](https://github.com/oven-sh/bun/pull/2126#pullrequestreview-1310371627)

**Comment by catdevnull** [comment]
would PRs using Wolfi have a chance to get merged?

**Comment by jbergstroem** [comment]
How about [distroless](https://github.com/GoogleContainerTools/distroless)? Is a Linux distribution required? Build on ubuntu/debian and copy over whats requird.

**Comment by moderation** [comment]
Distroless would be OK. The team behind Wolfi (working at Chainguard) are ex-Googlers that worked on a lot of the container tooling like Distroless. I think of Wolfi as the newer, shinier successor to Distroless

**Comment by dlorenc** [comment]
Hey! I'm with the Wolfi team and we'd be happy to help here.

**Comment by jbergstroem** [comment]
See #2369

**Comment by charlzyx** [comment]
i fixed it by alpine-pkg-glibc/2.34,  here is reference
> NOTE: Glibc 2.35 package is broken: https://github.com/sgerrand/alpine-pkg-glibc/issues/176, so we stick to 2.34 for now
https://github.com/Docker-Hub-frolvlad/docker-alpine-glibc/blob/master/Dockerfile

**Comment by catdevnull** [comment]
the "glibc alpine package" is broken again because **there's no such thing as glibc Alpine**, only a broken hack. please read the post in OP to understand why!

**Comment by catdevnull** [comment]
on the other hand, there's now a distroless image :partying_face: this will work properly because it's based in Debian with glibc :+1:

**Comment by Electroid** [comment]
We now have a distroless Docker image available at `oven/bun:distroless`. We will be tracking official support for MUSL here: #918

**Comment by catdevnull** [comment]
Sadly the Alpine glibc image [still exists](https://github.com/oven-sh/bun/blob/2327737b1424797f69d5979ca9b24bcda60fdae6/dockerhub/alpine/Dockerfile), which is problematic and misleading imo (see [there is no such thing as a "glibc based alpine image"](https://ariadne.space/2021/08/26/there-is-no-such-thing-as-a-glibc-based-alpine-image/))
