### ISSUE TITLE
Bun SQL postgres error: prepared statement already exists

### ISSUE THREAD

**Issue by TheGP** [oven-sh/bun#16844]
### What version of Bun is running?

1.1.36

### What platform is your computer?

Ubuntu

### What steps can reproduce the bug?

Not sure, it looks like sending the same request with different params like. It happened during run time, cant repeat it during test.

### What do you see instead?

```
Error: SyntaxError: Postgres error occurred
ERROR
ERROR
42P05
prepared statement "
		SELECT
			*
		FROM 
			accounts
		WHERE
			type = $1
		LIMIT $3
	.string.int4.int4" already exists
prepare.c
409
StorePreparedStatement
```

**Comment by TheGP** [comment]
I switched to postgres package, the problem dissapeared

**Comment by cirospaciari** [comment]
This issue was already fixed, can you try to upgrade to `v1.2.1`? if you are still running into this in the new version please reopen.

**Comment by TheGP** [comment]
I did and it was the same

**Comment by cirospaciari** [comment]
If you are still encountering this issue please reopen with a reproduction code and `bun --revision` result. This was fixed before 1.2.0 release.

**Comment by tri2820** [comment]
This still happens to me after upgrading.  

```sh
# .env
POSTGRES_URL=postgresql://postgres.<...>:<...>@aws-0-us-west-1.pooler.supabase.com:6543/postgres
```

```ts
const query = await sql`SELECT * FROM chunks`.execute();
await query;
```

```sh
↪ bun --revision
1.2.3-canary.94+3711280d4
```

It seems that the query runs fine the first time, then consistently fails until some time later (I guess until the connection is closed?), then works again (only the first time and then fails).
