### ISSUE TITLE
SQL: loses connection after timeout

### ISSUE THREAD

**Issue by jakeg** [oven-sh/bun#17178]
### What version of Bun is running?

1.2.2+c1708ea6a

### What platform is your computer?

Linux 5.15.167.4-microsoft-standard-WSL2 x86_64 x86_64

### What steps can reproduce the bug?

Sample code:

```js
import { sql } from 'bun'

Bun.serve({
  async fetch (req) {
    await sql`SELECT 'hello world'`
    return new Response('hi')
  }
})
```

Using a `.env` file with a `POSTGRES_URL` that connects to either Supabase's "Session pooler" or their "Transaction pooler".

Works fine until you don't do any requests (and thus SQL queries) for ~30+ seconds, then next time you try a request I presume the pool of connections have been closed due to an idle timeout, but no attempt is made to reconnect. The request hangs then this error appears:

```
[Bun.serve]: request timed out after 10 seconds. Pass `idleTimeout` to configure.
```

Am I supposed to do something manually to create new connections in the pool? I assumed that would be automatic.

Only way to fix is to restart the server, then of course it will happen again if no queries for 30+ secondds.

**Comment by jakeg** [comment]
Here's some code which shows this with just a timeout and no server needed. It seems like it's 60s+ not 30s that causes the issue:

```js
import { sql } from 'bun'

let timeout = 65
let count = 0
let query = async () => {
  console.log(`Trying ${++count}...`)
  await sql`SELECT 'hello world'`
  console.log('worked.')
}

await query()
console.log(`Trying again in ${timeout}s`)
setTimeout(query, timeout * 1_000)
```

**Comment by RiskyMH** [comment]
@jakeg can you try canary as I believe this has been fixed.

```zig
bun upgrade --canary
```

**Comment by jakeg** [comment]
Just upgraded (`1.2.3-canary.48+584db03a7`) and it's still a bug.

**Comment by cirospaciari** [comment]
The error:
```bash
[Bun.serve]: request timed out after 10 seconds. Pass `idleTimeout` to configure.
```

In this case`idleTimeout` is from `Bun.serve` take a look in https://bun.sh/docs/api/http#idletimeout and https://bun.sh/docs/api/http#server-timeout-request-seconds-custom-request-timeouts

SQL connection should reconnect if an `idleTimeout` happens but its not the error that showed. 
For the SQL it self you can increase the `maxLifetime` of the connection and `idleTimeout` so the query can be completed. See https://bun.sh/docs/api/sql#connection-options.

```ts
const sql = new SQL({
  host: "localhost",
  port: 5432,
  user: "bun",
  password: "bunbunbun",
  database: "bun",
  idleTimeout: 120,
});
const server = Bun.serve({
  idleTimeout: 120, // in seconds, 0 to disable but be careful
  async fetch(req) {
    if (req.url.endsWith("/timeout")) {
      await sql`SELECT pg_sleep(30)`; // will take 30 seconds to complete
    } else {
      await sql`SELECT 1`;
    }
    return new Response("hi");
  },
});

await fetch(server.url + "/timeout")
  .then(console.info)
  .catch(console.error);
await fetch(server.url).then(console.info).catch(console.error);
``` 

or you can also use `server.timeout` only when needed (safer)

```
const server = Bun.serve({
  async fetch(req) {
    if (req.url.endsWith("/timeout")) {
      server.timeout(req, 120); // long query expected
      await sql`SELECT pg_sleep(30)`; // will take 30 seconds to complete
    } else {
      await sql`SELECT 1`;
    }
    return new Response("hi");
  },
});
```


using the code I showed but without setting idleTimeout we get the output:

```bash
error: The socket connection was closed unexpectedly. For more information, pass `verbose: true` in the second argument to fetch()
  path: "http://localhost:3000//timeout",
 errno: 0,
  code: "ConnectionClosed"


Response (2 bytes) {
  ok: true,
  url: "http://localhost:3000/",
  status: 200,
  statusText: "OK",
  headers: Headers {
    "content-type": "text/plain;charset=utf-8",
    "date": "Tue, 11 Feb 2025 19:39:31 GMT",
    "content-length": "2",
  },
  redirected: false,
  bodyUsed: false,
  Blob (2 bytes)
}
```

Setting the proper timeout expecting long queries:

```bash
Response (2 bytes) {
  ok: true,
  url: "http://localhost:3000//timeout",
  status: 200,
  statusText: "OK",
  headers: Headers {
    "content-type": "text/plain;charset=utf-8",
    "date": "Tue, 11 Feb 2025 19:40:41 GMT",
    "content-length": "2",
  },
  redirected: false,
  bodyUsed: false,
  Blob (2 bytes)
}
Response (2 bytes) {
  ok: true,
  url: "http://localhost:3000/",
  status: 200,
  statusText: "OK",
  headers: Headers {
    "content-type": "text/plain;charset=utf-8",
    "date": "Tue, 11 Feb 2025 19:40:41 GMT",
    "content-length": "2",
  },
  redirected: false,
  bodyUsed: false,
  Blob (2 bytes)
}
```

In this test even after a connection closed I was able to run another query just fine in latest canary revision `1.2.3-canary.63+321500c62`. If you have other Issues with SQL reconnection or even Bun.serve please post a code that can reproduce the error and reopen.

**Comment by jakeg** [comment]
@cirospaciari sorry, my original bug report should have never included the `Bun.serve()` code - I understand the `idleTimeout` is from there and that just caused confusion.

I'm using Supabase PostgreSQL here with their default settings. I'm still getting the same bug (trying on canary `1.2.3-canary.63+321500c62`). Here's the code I'm using:

```js
import { sql } from 'bun'

let timeout = 65
let count = 0
let query = async () => {
  console.log(`Trying ${++count}...`)
  await sql`SELECT 'hello world'`
  console.log('worked.')
}

await query()
console.log(`Trying again in ${timeout}s`)
setTimeout(query, timeout * 1_000)
```

And the output:
```
Trying 1...
worked.
Trying again in 65s
Trying 2...
```
... at which point it just hangs still, seemingly forever.

I don't have a local PostgreSQL database I can try against, just the Supabase one. Maybe its based on some sort of Supabase default? But again, I would expect Bun to be reconnecting or something, not just hanging.

I just tried changing to this instead:

```js
import { SQL } from 'bun'

let sql = new SQL({
  url: process.env.POSTGRES_URL,
  maxLifetime: 0
})

// ...
```

... and still hanging.

This, however, **works without hanging**:

```js
let sql = new SQL({
  url: process.env.POSTGRES_URL,
  idleTimeout: 30
})
```

Is this expected behaviour? I'm guessing not.

**Comment by cirospaciari** [comment]
> [@cirospaciari](https://github.com/cirospaciari) sorry, my original bug report should have never included the `Bun.serve()` code - I understand the `idleTimeout` is from there and that just caused confusion.
> 
> I'm using Supabase PostgreSQL here with their default settings. I'm still getting the same bug (trying on canary `1.2.3-canary.63+321500c62`). Here's the code I'm using:
> 
> import { sql } from 'bun'
> 
> let timeout = 65
> let count = 0
> let query = async () => {
>   console.log(`Trying ${++count}...`)
>   await sql`SELECT 'hello world'`
>   console.log('worked.')
> }
> 
> await query()
> console.log(`Trying again in ${timeout}s`)
> setTimeout(query, timeout * 1_000)
> And the output:
> 
> ```
> Trying 1...
> worked.
> Trying again in 65s
> Trying 2...
> ```
> 
> ... at which point it just hangs still, seemingly forever.
> 
> I don't have a local PostgreSQL database I can try against, just the Supabase one. Maybe its based on some sort of Supabase default? But again, I would expect Bun to be reconnecting or something, not just hanging.
> 
> I just tried changing to this instead:
> 
> import { SQL } from 'bun'
> 
> let sql = new SQL({
>   url: process.env.POSTGRES_URL,
>   maxLifetime: 0
> })
> 
> // ...
> ... and still hanging.
> 
> This, however, **works without hanging**:
> 
> let sql = new SQL({
>   url: process.env.POSTGRES_URL,
>   idleTimeout: 30
> })
> Is this expected behaviour? I'm guessing not.

Is not the expected behavior, really weird that you are facing this, will check using supabase, I cannot replicate this error with a local database with is weird, thank you for all information will investigate further

**Comment by jakeg** [comment]
Can confirm that on Canary (`1.2.3-canary.70+1bb1f59b9`) since the PR landed this now works with just `import { sql } from 'bun'`. Thank you!
