### ISSUE TITLE
bun-types 1.2.5 interferring with bun-plugin-dts

### ISSUE THREAD

**Issue by alxjrvs** [oven-sh/bun#18147]
### What version of Bun is running?

1.2.5+013fdddc6

### What platform is your computer?

Darwin 24.3.0 arm64 arm

### What steps can reproduce the bug?

1. `bun init` with the `Library` option. 
2. run `bun add -d bun-plugin-dts`. 
3. create a `build.ts` file with the following contents: 

```ts
import dts from 'bun-plugin-dts'

await Bun.build({
  entrypoints: ['./index.ts'],
  outdir: './dist',
  sourcemap: 'inline',
  plugins: [dts()]
})
```
4. run `bun run build.ts`

### What is the expected behavior?

I get a fully built app inside of `/dist`, with a `index.js` and a `index.d.ts`. 

### What do you see instead?

I get a stacktrace with the following error: 

`Cannot find symbol for node "ShellOutput" in "ShellOutput" from "/Users/jarvis/Code/foo/node_modules/bun-types/bun.d.ts"`. 

### Additional information

This only appears on version `1.2.5` of `bun-types`. Affixing the version of `bun-types` to `1.2.4` fixes the issue.

**Comment by alii** [comment]
Thanks for reporting, will fix this soon.

Yes you can either drop down to 1.2.4 or enabling `skipLibCheck` should fix this.

**Comment by nowm** [comment]
@Jarred-Sumner Any info when updated types will be available in NPM? Current `latest` version still has this error.

**Comment by nowm** [comment]
As a temporary workaround for people who have found this issue.

```shell
bun r @types/bun bun-types
bun i -d bun-types@canary
```

**Comment by alii** [comment]
@nowm This will ship in 1.2.6 since @types/bun does releases at the same of Bun itself.

We recommend this as a workaround for loading canary versions of `bun-types`

```jsonc
{
	"devDependencies": {
		"@types/bun": "1.2.5" // You probably already have this
	},
	"resolutions": {
		"bun-types": "canary" // Force `bun-types` to install canary version
	}
}
```

Once 1.2.6 ships, you can remove the resolution and revert back to the stable version of the types.

**Comment by nowm** [comment]
> [@nowm](https://github.com/nowm) This will ship in 1.2.6 since @types/bun does releases at the same of Bun itself.
> 
> We recommend this as a workaround for loading canary versions of `bun-types`
> 
> {
> 	"devDependencies": {
> 		"@types/bun": "1.2.5" // You probably already have this
> 	},
> 	"resolutions": {
> 		"bun-types": "canary" // Force `bun-types` to install canary version
> 	}
> }
> 
> Once 1.2.6 ships, you can remove the resolution and revert back to the stable version of the types.

Oh, thanks for a better `canary` alternative. My version (deleted the message) actually did not solve problem.

**Comment by mikan3rd** [comment]
@Jarred-Sumner  @alii 
`"@types/bun": "1.2.6"` also causes a similar error, so I would like to reopen this Issue.
```
error: Cannot find symbol for node "constants" in "typeof import("node:trace").constants
```

**Comment by alii** [comment]
> [@Jarred-Sumner](https://github.com/Jarred-Sumner) [@alii](https://github.com/alii) `"@types/bun": "1.2.6"` also causes a similar error, so I would like to reopen this Issue.
> 
> ```
> error: Cannot find symbol for node "constants" in "typeof import("node:trace").constants
> ```

This is fixed already, could you try updating @types/bun to 1.2.8? Thanks

**Comment by mountEvarus** [comment]
I think 1.2.19 and above, as of this comment, are having the same issue again:
```
Cannot find symbol for node "PerformanceResourceTiming" in "import("node:perf_hooks").PerformanceResourceTiming"
```
