### ISSUE TITLE
MySql Access Denied - failed to connect via TLS Caching SHA2 password

### ISSUE THREAD

**Issue by neves** [oven-sh/bun#22312]
### What version of Bun is running?

1.2.21

### What platform is your computer?

Darwin 23.6.0 arm64 arm

### What steps can reproduce the bug?

I can connect with mysql2, but not Bun.sql

```typescript
import MySql from "mysql2/promise"
const mysql2 = await MySql.createConnection({
  uri: Bun.env.DATABASE_URL
})

console.log(await mysql2.query("SELECT VERSION()"))
await mysql2.end()
console.log(await Bun.sql`SELECT VERSION()`)
```

### What is the expected behavior?

```
[
  [
    {
      "VERSION()": "8.0.43-0ubuntu0.22.04.1",
    }
  ], [
    `VERSION()` VARCHAR(23) NOT NULL
  ]
]
[
  {
    "VERSION()": "8.0.43-0ubuntu0.22.04.1",
  }, count: 1, command: null, lastInsertRowid: 0,
  affectedRows: 0
]
```

### What do you see instead?

```
[
  [
    {
      "VERSION()": "8.0.35",
    }
  ], [
    `VERSION()` VARCHAR(6) NOT NULL
  ]
]
2 | (function (){"use strict";// build/release/tmp_modules/internal/sql/errors.ts
3 | var $;
4 | 
5 | class SQLError extends Error {
6 |     super(message);
        ^
MySQLError: Access denied for user 'avnadmin'@'160.20.207.216' (using password: YES)
    errno: 1045,
 sqlState: "28000",
     code: "ERR_MYSQL_SERVER_ERROR"

      at new SQLError (internal:sql/errors:6:5)
      at new MySQLError (internal:sql/errors:82:5)
      at wrapError (internal:sql/mysql:14:10)
      at #onClose (internal:sql/mysql:224:22)

Bun v1.2.22-canary.1+0c93d0aaa (macOS arm64)
```

### Additional information

I tried canary and bun-22132 https://github.com/oven-sh/bun/issues/22178

**Comment by RiskyMH** [comment]
Hopefully fixed by https://github.com/oven-sh/bun/pull/22132. If you want to try it now you can run:
```zig
bunx bun-pr 22132

// and use like 
bun-22132 ./index.ts
```

**Comment by RiskyMH** [comment]
yay thanks for confirming!

**Comment by neves** [comment]
@rodhoward I can connect locally too, but if fails when connecting to PlanetScale, DigitalOcean, etc.
I can connect Remote when the user is using password **MySQL native password** but not when it's using **Caching SHA2 password**

Can you try with those urls (I created a free database at [aiven.io](https://console.aiven.io))
### Native
```js
DATABASE_URL="mysql://native:AVNS_XlKJd6UfdtTvhM22wKI@mysql-neves.g.aivencloud.com:22168/defaultdb" bun -p'await Bun.sql`SELECT 1`'
[
  {
    "1": 1,
  }, count: 1, command: null, lastInsertRowid: 0, affectedRows: 0
]
```
### Sha2
```js
DATABASE_URL="mysql://sha2:AVNS_Sz4UWljH_Xkit5lkZWp@mysql-neves.g.aivencloud.com:22168/defaultdb" bun -p'await Bun.sql`SELECT 1`'
 9 |   createQuery: createMySQLQuery,
10 |   init: initMySQL
11 | } = @lazy(13);
12 | function wrapError(error) {
13 |   if (Error.isError(error))
14 |   return new MySQLError(error.message, error);
              ^
MySQLError: Access denied for user 'sha2'@'160.20.204.58' (using password: YES)
    errno: 1045,
 sqlState: "28000",
     code: "ERR_MYSQL_SERVER_ERROR"

      at wrapError (internal:sql/mysql:14:10)
      at #onClose (internal:sql/mysql:224:22)

Bun v1.2.22-canary.81+d42f536a7 (macOS arm64)
```

**Comment by neves** [comment]
@cirospaciari still getting exactly same error:
```
DATABASE_URL="mysql://sha2:AVNS_Sz4UWljH_Xkit5lkZWp@mysql-neves.g.aivencloud.com:22168/defaultdb" \
bun-22132 -p'await Bun.sql`SELECT 1`'
```
It happens only using **Caching SHA2 password**

Since PlanetScale requires `?sslmode=require` it timeouts instead of the error above

**Comment by cirospaciari** [comment]
@neves can you wait 2h and try canary again? The fix should be available after canary is updated.

**Comment by neves** [comment]
@cirospaciari using canary now it works only if using sslmode=require
| password | sslmode | result |
|--------|--------|--------|
| native | off | working |
| native | on | working |
| sha2 | off | _error_ |
| sha2 | on | working | 

At least I have a possible working version. Thank you for the super fast fix. You can reopen this issue or should I open another one for the above error?

**Comment by madebyais** [comment]
I just tested with the bun canary version, it works

**Comment by RiskyMH** [comment]
@madebyais you are using canary version right?

I'll reopen as `sslmode` false with `sha2` was identified to not fix it fully

**Comment by madebyais** [comment]
> [@madebyais](https://github.com/madebyais) you are using canary version right?
> 
> I'll reopen as `sslmode` false with `sha2` was identified to not fix it fully

Yups, just tried the canary version and it works properly for now
