### ISSUE TITLE
Support self signed certificate

### ISSUE THREAD

**Issue by rvitorgomes** [oven-sh/bun#2915]
### What is the problem this feature would solve?

I'm trying to use edgedb javascript client (edgeql-js) but it fails to connect to my local edge server.

error: network error: DEPTH_ZERO_SELF_SIGNED_CERT: self signed certificate
 code: "4278256384"
 
 Version: 
 "edgedb": "^1.2.2",
 "bun": "0.6.1",
 
 My code:
 ```typescript
 import { Elysia } from 'elysia'
import { createClient } from "edgedb"

const client = createClient({
    // dsn: "edgedb://edgedb@localhost:5656/edgedb"
})
await client.ensureConnected()

const app = new Elysia()
    .get('/', () => 'Hello Elysia 2')
    .get('/e', async () => {
        return await client.query("select 2 + 2");
    })
    .listen(3000)

console.log(`🦊 Elysia is running at ${app.server?.hostname}:${app.server?.port}`)

 ```
 
 The error:
 
![image](https://github.com/oven-sh/bun/assets/14111893/30991dd9-ff26-4aa9-ad7f-cedfc28c963a)

### What is the feature you are proposing to solve the problem?

Seems to be a network package missing feature.

**Comment by t0xicCode** [comment]
This seems more like an EdgeDB issue: https://www.edgedb.com/docs/reference/connection#granular-parameters
It provides a method to disable certificate validation, which would allow it to accept self-signed certificates.

**Comment by rvitorgomes** [comment]
Update:
I ran node with the same code and worked
Also tried disable all security, but it still shows an error.
_The server doesn't support the edgedb-binary protocol_
```typescript
export const client = createClient({
   tlsSecurity: "insecure" 
});
```
What I'm trying to reason now is about their "binary protocol" has something that is missing....
I run node with the same code and worked

https://www.edgedb.com/docs/reference/protocol/index

**Comment by cirospaciari** [comment]
@rvitorgomes Boa tarde, poderia fazer um teste versão `v0.6.3`? foram feitas algumas melhorias, talvez funcione agora.

**Comment by rvitorgomes** [comment]
Tried with this example:
```typescript
// example.ts
const e = require('edgedb');

(async () => {
    const client = e.createClient({ 
    });
    const res = await client.query("select 2 + 2");
    process.stdout.write(res.toString());
    process.stdout.write('\n');
})();

In node v17:.
ts-node example.ts

```
![image](https://github.com/oven-sh/bun/assets/14111893/4a4b1b15-e53a-4cfa-be40-6a8d229718e8)


In bun v0.6.3
bun example.ts
![image](https://github.com/oven-sh/bun/assets/14111893/f4d7f750-aceb-41a1-b2d2-cd2ec6ad4ca7)

**Comment by e3dio** [comment]
I actually had this issue earlier today with MongoDB. Confirm working correctly now in `v0.6.3`

**Comment by rvitorgomes** [comment]
> I actually had this issue earlier today with MongoDB. Confirm working correctly now in `v0.6.3`

I'm sure it's on 0.6.3

![image](https://github.com/oven-sh/bun/assets/14111893/c0b155ee-33d8-4dd3-b05b-82c90dbb7026)

I still think something about EdgeDB communication that bun still don't have fully implemented...

**Comment by e3dio** [comment]
Your error looks different, my issue that was fixed was: `error: SELF_SIGNED_CERT_IN_CHAIN` when trying to connect to MongoDB Atlas from AWS EC2

**Comment by rvitorgomes** [comment]
```typescript
// example.ts
import {createClient, createHttpClient} from 'edgedb';

const client = createHttpClient({
    instanceName: "edgedb_demo"
});
client.ensureConnected()

const res = await client.query("select 2 + 2")

console.log("Hello via Bun!", res);
```
Here it works properly, using the http communication,

**Comment by cirospaciari** [comment]
Probably it's some `tls` feature missing or diverging, we will investigate further, thanks for reporting.

**Comment by rvitorgomes** [comment]
> Your error looks different, my issue that was fixed was: `error: SELF_SIGNED_CERT_IN_CHAIN` when trying to connect to MongoDB Atlas from AWS EC2

Yeah, I think it also was fixed and another error apeared...maybe I'll check the versions error diff later.

**Comment by rvitorgomes** [comment]
Retried with 0.6.7, same.
Any updates? @cirospaciari

**Comment by cirospaciari** [comment]
> Retried with 0.6.7, same.
> Any updates? @cirospaciari 

Not yet but soon will be, working on adding more features on TLS

**Comment by 0x241F31** [comment]
Sorry, but was this resolved? I still get this error on Bun 1.0.7

```
2 | Object.defineProperty(exports, "__esModule", { value: true });
3 | exports.prettyPrintError = exports.EdgeDBError = void 0;
4 | const buffer_1 = require("../primitives/buffer");
5 | class EdgeDBError extends Error {
6 |     constructor(message, options) {
7 |         super(undefined, options);
            ^
error: network error: ECONNREFUSED: Failed to connect
 code: "4278256384"

      at new EdgeDBError (/home/foxpro/craft/sferadel/dev/api/node_modules/.pnpm/edgedb@1.4.0/node_modules/edgedb/dist/errors/base.js:7:8)
      at new ClientError (:1:32)
      at new ClientConnectionError (:1:32)
      at new ClientConnectionClosedError (:1:32)
      at _onError (/home/foxpro/craft/sferadel/dev/api/node_modules/.pnpm/edgedb@1.4.0/node_modules/edgedb/dist/rawConn.js:146:23)
      at node:net:331:34
      at processTicksAndRejections (:61:76)
      ```
