### ISSUE TITLE
Support workspaces without `workspace:` protocol

### ISSUE THREAD

**Issue by raulfdm** [oven-sh/bun#4676]
### What version of Bun is running?

1.0.0+822a00c4d508b54f650933a73ca5f4a3af9a7983

### What platform is your computer?

Darwin 23.0.0 arm64 arm

### What steps can reproduce the bug?

While trying to migrate to bun workspace, I noticed that `bun` isn't able to resolve internal packages that contain organization alias.

Repository: https://github.com/devraul/bun-workspace-organization-error

Steps to reproduce:
 1. Clone the project
 2. Try to run `bun install --yarn`
 3. see the error
   ```
   error: package "@monorepo/math" not found registry.npmjs.org/@monorepo/math 404
   error: @monorepo/math@* failed to resolve
   ```

Notice that this only happens because I have `@monorepo` in the package name.

If you remove `@monorepo` and run the installation command, it will work fine.

### What is the expected behavior?

Resolves the internal package with organization scope in its name.

### What do you see instead?

https://github.com/oven-sh/bun/assets/12464600/56c25076-9247-41d4-92c8-0d66d85ccb21

### Additional information

Maybe related https://github.com/oven-sh/bun/issues/4628

**Comment by benvan** [comment]
@raulfdm I had the same problem, but have discovered a workaround / partial solution?

1. Modify your dependency on `"@monorepo/math": "*"` to be `"@monorepo/math": "workspace:*"`
2. Delete bun.lockb and try again (bun install)

The second step seems to be critical - if you don't, bun will instead give the following error (which does seem like a bug):
```
bun install v1.0.0 (822a00c4)


error: workspace dependency "@monorepo/math" not found

Searched in "./*"

Workspace documentation: https://bun.sh/docs/install/workspaces
```

EDIT: Seems I celebrated too soon. Whilst the installation works, bun can't resolve / import "@monorepo/math" at runtime
```
error: Cannot find module "@monorepo/math" from "/Users/ben/projects/bun-workspace-organization-error/test.ts"
```

EDIT 2: Ah. That's because in your example, the "@monorepo/math" package has an invalid config. It's looking for a file called "index.ts" in the package root but there isn't one
```
// in packages/math/package.json change this
"module": "index.ts"
// to this
"module": "src/index.ts"
```

**Comment by raulfdm** [comment]
Thanks for the inputs @benvan .

I've fixed the entry point in the demo repository.

Indeed, switching from `*` to `workspace:*` did the trick, but then we had to update the docs. It's misleading to the actual behavior. 🤔

**Comment by is-it-ayush** [comment]
> Indeed, switching from * to workspace:* did the trick, but then we had to update the docs. It's misleading to the actual behavior. 

Yep! Switching to workspace protocol fixed it. I wonder if the docs are either wrong or I missed a step. Either way, hope somebody from the team helps.

**Comment by artberri** [comment]
Is switching from `*` to `workspace:*` just a workaround for now or the expected behavior? In our case, to be able to transition from node@20/yarn@1 to bun with baby steps we expect the package.json files to be compatible.

A good first approach for us could be to still run the app with node, but start running the unit tests with bun, but I think that this will not be possible unless the package.json syntax is compatible.

**Comment by dylang** [comment]
I created a PR to update the docs: https://github.com/oven-sh/bun/pull/5379

**Comment by emanuel-lundman** [comment]
Shouldn't the issue be resolved to  not need the workspace prefix instead. Better to fix the issue then alter the docs for the workaround? Or is it supposed to need the workspace prefix?

I know there were some other issue after adding the prefix. It helped to resolve the dependencies to get it running but everything doesn't work with the prefix either. Had some issue with another command not liking the prefix when I tried it in our monorepo. 
Can't remember exactly which command it was but can absolutely try to find it again later.

**Comment by Jarred-Sumner** [comment]
This bug was fixed in Bun v1.1.8:
```ts
❯ rm -rf node_modules ../../node_modules/ ../../bun.lockb
❯ bun-1.1.8 install
bun install v1.1.8 (89d25807)

 + @monorepo/math@workspace:packages/math
 + vite-project@workspace:apps/vite-project
 + bun-types@1.0.1 (v1.1.18 available)
 + typescript@5.2.2 (v5.5.3 available)

 84 packages installed [360.00ms]

 Blocked 1 postinstall. Run `bun pm untrusted` for details.
```

Bun v1.1.7 (where it did not work):
```ts
❯ rm -rf node_modules ../../node_modules/ ../../bun.lockb
❯ bun-1.1.7 install
bun install v1.1.7 (b0b7db5c)
  🔍 @monorepo/math [1/1]
error: package "@monorepo/math" not found registry.npmjs.org/@monorepo%2fmath 404
error: @monorepo/math@* failed to resolve
```

We've released 10 updates to Bun since Bun v1.1.8 and we've continued to make several improvements to workspaces support in `bun install`.

Let us know if you're still running into issues like this and we'll be happy to fix things.

**Comment by raulfdm** [comment]
@Jarred-Sumner thank you so much. Can confirm the problem is fixed :)

**Comment by Jarred-Sumner** [comment]
All credit to @dylan-conway :), I did almost nothing

**Comment by csmikle** [comment]
But is the requirement to use workspace: prefix still present today? Like others said I'm looking for package.json compatability and would just like to hear context about why it's needed. 

Even with adding the prefix and changing imports I had issues moving a node project to Bun in July and would like to try again now... just wondering what Matt have improved on this front

**Comment by olistrik** [comment]
@csmikle I have a project with multiple workspaces, the only mention of them is in the root package.json where I declare the globs.

The sub-projects seem to resolve inter-project dependencies just fine even with semver ranges or an asterisk. `bun pm ls` lists the resolved dependencies with pathed versions such as `foo@workspace:projects/bar"`.

My LSP even hops to definitions in the correct source files rather than to something in the node_modules.

**Comment by xsamueljr** [comment]
Very old issue but it's what it popped up on my google search. I'm not able to make it work, I have a package for the frontend, another one for the backend, a dev dependency in the frontend package to the backend one (for types, elysia and RPC basically) and it just completely ignores it. It's in the output of `bun pm ls` and in the node_modules folder of the frontend package

https://github.com/xsamueljr/inventory

**Comment by xsamueljr** [comment]
In case this helps someone; fixed by adding `"main"` and `"types"` to the `package.json` of the backend package
