### ISSUE TITLE
Reading private registry fails after bun.lockb is created 

### ISSUE THREAD

**Issue by waganse** [oven-sh/bun#5721]
### What version of Bun is running?

1.0.2+37edd5a6e389265738e89265bcbdf2999cb81a49

### What platform is your computer?

Darwin 22.4.0 arm64 arm

### What steps can reproduce the bug?

1. Configure private registry in `bunfig.toml`
```
[install.scopes]
"@myorg" = { url = "https://npm.pkg.github.com/:_authToken=githubpat" }
```

2. Run `bun install`
Successfully done.

3. Run `bun install` again and get 404 error
```
error: package "@myorg/package" not found npm.pkg.github.com/@myorg/package 404
```

4. Remove `bun.lockb` and re-run `bun install`
Successfully done.

### What is the expected behavior?

Apply config in `bunfig.toml` for `bun install` with `bun.lockb`.

**Comment by eremiev** [comment]
I notice that Bun reads/concatenates the URL differently. I fixed my issue but adding an extra "/" at the end of the URL.
try:

```
[install.scopes]
"@myorg" = { url = "https://npm.pkg.github.com/:_authToken=githubpat/" }
```

**Comment by waganse** [comment]
> I notice that Bun reads/concatenates the URL differently. I fixed my issue but adding an extra "/" at the end of the URL. try:
> 
> ```
> [install.scopes]
> "@myorg" = { url = "https://npm.pkg.github.com/:_authToken=githubpat/" }
> ```

@eremiev I tried it, and got another error.
```
error: forbidden while loading "@myorg/package" 403
```

**Comment by Jarred-Sumner** [comment]
Please upgrade to canary and give it another try

```
bun upgrade --canary
```

**Comment by waganse** [comment]
@Jarred-Sumner Still getting an error... 
I tried with these two cases;`@myorg = { url = "https://npm.pkg.github.com/:_authToken=mypat" }`
and `@myorg = { url = "https://npm.pkg.github.com/:_authToken=mypat/" }`.

[Result]
```
$ bun upgrade --canary
[2.20s] Upgraded.

Welcome to bun's latest canary build!

Report any bugs:

    https://github.com/oven-sh/bun/issues

Changelog:

    https://github.com/oven-sh/bun/compare/37edd5a6e389265738e89265bcbdf2999cb81a49...main

$ bun install         
bun install v1.0.3 (8677ae9f)
  🔍 @myorg/package [1/1] 
error: package "@myorg/package" not found npm.pkg.github.com/@myorg%2fpackage 404
  🔍 @myorg/package [1/1] 
error: @myorg/package@* failed to resolve
```

**Comment by iwt-jandwinger** [comment]
@waganse 
try again with lasted version 1.0.3, it's working for me! The path "/npm/meep/" is important !

> [install]
> registry = "https://registry.npmjs.org" # redeclare default!
> [install.scopes]
> "@meep" = { url = "https://xxxx-xxxxxxxxx.d.codeartifact.eu-west-1.amazonaws.com/npm/meep/" , token = "myToken"}

**Comment by waganse** [comment]
@iwt-jandwinger 
How does it work for github private packages?

**Comment by kevinpoot** [comment]
I'm having this issue as well inside Github Actions

**Comment by cwhsu1984** [comment]
I try following [registry-scope](https://bun.sh/guides/install/registry-scope) and https://github.com/renovatebot/renovate/issues/24460#issuecomment-1751325824, but I always get 404.

my .npmrc is like
```
@xxx:registry=http://myrepo.com/api/v4/packages/npm/
@yyy:registry=http://myrepo.com/api/v4/packages/npm/
//myrepo.com/api/v4/:_authToken=SomeToken
```

bunfig.1.toml
```
[install.scopes]
"@xxx" = { url = "http://myrepo.com/api/v4/", token="SomeToken" }
"@yyy" = { url = "http://myrepo.com/api/v4/", token="SomeToken" }
```

bunfig.2.toml
```
"@xxx" = { url = "http://myrepo.com/api/v4/:_authToken=SomeToken" }
"@yyy" = { url = "http://myrepo.com/api/v4/:_authToken=SomeToken" }
```


The error that I get is like
```
λ npx bun install
[0.00ms] ".env.production"
bun install v1.1.7-canary.1 (b0b7db5c)
  � Resolving...
GET http://myrepo.com/api/v4/@xxx/mypackage/-/mypackage-1.0.3.tgz - 404
  � Resolving...
GET http://myrepo.com/api/v4/@xxx/mypackag2/-/mypackag2-1.0.2.tgz - 404
  � Resolving...
GET http://myrepo.com/api/v4/@xxx/mypackag3/-/mypackag3-0.0.8.tgz - 404
```

**Comment by genu** [comment]
Its been a couple of years now, has there been any progress on this, or is there any workaround possible?

**Comment by Jarred-Sumner** [comment]
@genu This was fixed in Bun v1.1.13 via https://github.com/oven-sh/bun/pull/11606 and related PRs.

If you continue to run into this on a version of Bun >= 1.1.13, please leave a comment and we'll re-open it
