### ISSUE TITLE
bun install --ignore-scripts should take an optional list of packages

### ISSUE THREAD

**Issue by mrdomino** [oven-sh/bun#7605]
### What is the problem this feature would solve?

I recently had my build broken by `protobufjs` trying to run `node scripts/postinstall` in its `postinstall` target. (Incidentally, this happened on upgrading to the latest `oven/bun:alpine` from one that was about three weeks old. If that is a bug, I can report it separately.)

I was able to retrieve a working build by passing `--ignore-scripts` in my Dockerfile, but this blanket-disables all scripts for all packages, whereas I only want to disable the one that was broken.

### What is the feature you are proposing to solve the problem?

Passing `--ignore-scripts=protobufjs` or even `--ignore-scripts=protobufjs:postinstall` would let me more selectively target just the script I don't want to run, without surprising behavior if other packages need other scripts to work.

**Comment by paperclover** [comment]
a tangentally related idea, cc @dylan-conway, what if `trustedDependencies` could be used as a negation like `["-protobufjs"]` to ignore their script.

though looking into this a bit closer.

- protobufjs' postinstall script doesnt do anything helpful (it prints warnings but most package managers do not show script logs unless they fail)
- a bug in bun causes this script to fail

**Comment by ricardojmendez** [comment]
I can confirm the report - installing works with bun's docker image up until 1.0.16, but broke in 1.0.17.

What workaround are you using, @mrdomino? Staying on an older image, or something else?

**Comment by ricardojmendez** [comment]
This issue persists on 1.0.18+36c316a24 - how it manifests with protobufjs is that it ends up stuck on the post-install script, instead of aborting like it did on 1.0.17.

![Screenshot 2023-12-16 at 09 40 54](https://github.com/oven-sh/bun/assets/31263/7429e05b-6929-4880-abbd-9f2619f4903f)

**Comment by Jarred-Sumner** [comment]
If you set `”trustedDependencies”: []` in package.json, it will prevent any dependencies scripts from loading. That should do most of what you want.

**Comment by ricardojmendez** [comment]
> If you set `”trustedDependencies”: []` in package.json, it will prevent any dependencies scripts from loading. That should do most of what you want.

Thanks @Jarred-Sumner - that does not help with the protobufjs install issue, though.

**Comment by mrdomino** [comment]
> I can confirm the report - installing works with bun's docker image up until 1.0.16, but broke in 1.0.17.
> 
> What workaround are you using, @mrdomino? Staying on an older image, or something else?

Blanket ignoring scripts happens to work for my case, so I am doing that.

**Comment by paperclover** [comment]
> If you set `”trustedDependencies”: []` in package.json, it will prevent any dependencies scripts from loading. That should do most of what you want.

this is not true, we always run our default list. this should probably change

**Comment by ricardojmendez** [comment]
> This issue persists on 1.0.18+36c316a24 - how it manifests with protobufjs is that it ends up stuck on the post-install script, instead of aborting like it did on 1.0.17.
> 

This has disappeared on 1.0.19+906f86d6f

**Comment by paperclover** [comment]
yes, the bug affecting protobufjs was fixed but the feature request here still stands

**Comment by wesleycoder** [comment]
I've just run into this issue but when installing `pixijs` instead, which depends on `canvas`.

Adding `--ignore-scripts` to every bun install will make the installation succeed.
The `trustedDependencies` trick did not solve this and the post install script still tried to compile the gyp module.

Following this to see if any other options arise.
