### ISSUE TITLE
`bunx` postinstall throws "could not determine executable to run for package exec" 

### ISSUE THREAD

**Issue by Lol1chw** [oven-sh/bun#9841]
### What version of Bun is running?

1.1.0+5903a6141

### What platform is your computer?

Microsoft Windows NT 10.0.22631.0 x64

### What steps can reproduce the bug?

1. ```bun create vite```
   1. Project Name - reproduce-bun-bug
   2. Select Framework - Vue
   3. Select a variant - Customize with create-vue
   4. Select the options you need
   5. ```bun install```
2. Following the [shadcn-vue installation guide](https://www.shadcn-vue.com/docs/installation/vite.html)
  1. bunx --bun shadcn-vue@latest init

### What is the expected behavior?

[Successful launch of cli shadcn-vue](https://www.shadcn-vue.com/docs/installation/vite.html#run-the-cli)

### What do you see instead?

```bash
$ bunx --bun shadcn-vue@latest init
  ⚙️  vue-demi [1/1] error: could not determine executable to run for package exec      

error: postinstall script from "vue-demi" exited with 1
```

### Additional information

[Issue thread in discord](https://discord.com/channels/876711213126520882/1224594606512017460)

**Comment by Lol1chw** [comment]
UPD: I tried using the full command "bun x" instead of the alias and it worked
![bunx_workaround](https://github.com/oven-sh/bun/assets/94941930/64478bd3-f5d3-4d9a-b811-0d73015c2a0d)

# 🚧Workaround: 
Use ```bun x``` instead of the alias ```bunx```

**Comment by Jarred-Sumner** [comment]
Fixed by #9729

**Comment by Jarred-Sumner** [comment]
Fixed in #9729, please try again after running `bun upgrade --canary` in about an hour (or wait for Bun v1.1.1). Let us know if you run into this again.

**Comment by dkmnx** [comment]
I have experienced this in v1.1.8.

**Comment by jdkcoder** [comment]
same as bamontales, experienced this in Bun v1.1.8

**Comment by OliverWich** [comment]
Still (or again) present in Bun v1.1.10 (1.1.10+5102a9443)...

![image](https://github.com/oven-sh/bun/assets/35409274/8a3ddf7a-ddf0-493e-9532-f50ee412a471)

Curiously, the tip from @Lol1chw of using `bun x` instead of `bunx` works. Strange.

**Comment by Lucklj521** [comment]
Still present in Bun 1.1.18 and bun x instead of bunx also works.

**Comment by Lol1chw** [comment]
Reopen issue because the problem is still unresolved.

**Comment by forsureitsme** [comment]
Still present in Bun 1.1.29 and bun x instead of bunx still works.

**Comment by hahagu** [comment]
Can confirm that this is still present in 1.1.36 with shadcn-vue

**Comment by CosmoMyzrailGorynych** [comment]
Note: `bun x` versus `bunx` is most likely a fluke as just running the same `bunx` command can fix installation. For example, this is what happens when I try to install `@neutralinojs/cli` library.

**Comment by Arctomachine** [comment]
Encountered this problem with `create-next-app` in earlier versions, but not anymore.
In version 1.1.42 it happens for `bunx storybook@latest init`
```
bunx storybook@latest init
  ⚙️  esbuild [1/1] error: could not determine executable to run for package exec

error: postinstall script from "esbuild" exited with 1
```

Contrary to above post, running same command multiple times gives same error, but `bun x` worked

**Comment by RiskyMH** [comment]
I have come to find out some interesting details:
* `bunx my-package` works after second attempt (if it was postinstall issue)
* `bunx my-package@tag` doesn't work as forces cache clear
* `bunx my-package@1.1.1` works after second attempt
* `bun x my-package@tag` works though (even if `bunx` didn't), so it must _not_ be force clearing cache
* for the first one I think it stops working first time occasionally (probably every day) to clear cache to try to be latest

I am feeling like this is possibly a race condition on not letting postinstall finish and go straight to trying to run it.

**Comment by RiskyMH** [comment]
Update my initial theory was wrong, it appears like `bunx` behavior was slightly different in windows and the cli didn't account for this, **see my fix in #17076** 

---

There is still one issue I haven't worked out: `bunx supabase@latest`, this works well on linux and npm but:
```powershell
C:\>bunx supabase@latest
error: could not determine executable to run for package supabase

# installed on local project works though
C:\>bun add supabase
C:\>bunx supabase
```
I'm not sure the reason behind this, but if you go to the bunx cache folder and run `bun i` it will also work. So there must be some other issues with postinstall. All my above fix was doing was helping executing the package once it was installed (which explains why second attempt works)

**Comment by MordechaiHadad** [comment]
Have similar issue on latest version on windows (which is what prompted RIsky to comment here)

**Comment by RiskyMH** [comment]
If it works with `bun x <pkg>`, then it will work with my fix of `bunx` to be equal quality

**Comment by JulianMiguelAngle** [comment]
Man reopen di issue man

**Comment by rizkyhaksono** [comment]
Why is it work using bun x instead of bunx?

**Comment by rizkyhaksono** [comment]
> [@rizkyhaksono](https://github.com/rizkyhaksono) see what I wrote in [#17076](https://github.com/oven-sh/bun/pull/17076)
> 
> It should be working on latest Bun (released in `1.2.3`), so if you are still having this issue please let me know

I have 1.2.5 version, and it worked
Thank you
